### ISSUE TITLE
Simplify header inclusion and cmake list

### ISSUE THREAD

**Issue by skliper** [nasa/elf2cfetbl#22]
**Is your feature request related to a problem? Please describe.**
Complex CMakeList.txt header logic shouldn't be needed any more

**Describe the solution you'd like**
Include the now "external" headers for tables

**Describe alternatives you've considered**
None

**Additional context**
Related to https://github.com/nasa/cFE/pull/25

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Related changes here:
- The code should NOT include `cfe_tbl_internal.h` any more -- this is by definition an internal file, the tool does not and should not need to use any internal definitions from CFE_TBL.
- The references to `CFE_TBL_MAX_FULL_NAME_LEN` can be removed.  Use `sizeof(TableHeader.TableName)` instead, and the alignment logic can be removed because the user should have defined `CFE_MISSION_TBL_MAX_FULL_NAME_LEN` as a multiple of 4 anyway.

**Comment by jphickey** [comment]
On second look, both cases of `ByteAlignFileHeaders` and the associated command line option should probably be removed.  It has no purpose if we are enforcing that these values are a multiple of 4 already via compile time asserts.

**Comment by skliper** [comment]
@jphicky are you done with this one?  If so could you submit a pull request with the associated testing details?  It all looks good to me.
