### ISSUE TITLE
If you get a PATH_MAX undefined issue...

### ISSUE THREAD

**Issue by BaldBeacon** [nasa/elf2cfetbl#35]
The inclusion of the PATH_MAX has introduced a compilation error when compiling on linux systems. While this is a little confusing, the PATH_MAX definition is located in <linux/limits.h> not <limits.h> which is currently included [here](https://github.com/nasa/elf2cfetbl/blob/3c4be5954cccc845fb329b81872d94df3780d126/elf2cfetbl.c#L40).

1. Pull the latest build of the CFS that uses this tool (as of commit b7dcc71360467ce2443dff27ea6314199f5c3ef0)
2. Attempt to build using the sample cmake

**Expected behavior**
No compilation errors.

**System observed on:**
 - OS: Ubuntu 18.04.4 LTS
 - Versions: cFE 6.7.11, OSAL 5.0.10, PSP 1.4.7 for linux

**Comment by skliper** [comment]
-D_XOPEN_SOURCE=600

**Comment by skliper** [comment]
@BaldBeacon please confirm if this define works or not

**Comment by jphickey** [comment]
The _XOPEN_SOURCE=600 should be already included for all tools if using the supplied example `mission_build_custom.cmake` file in your CFE config, so I'm curious if this was somehow missing?

**Comment by skliper** [comment]
I read this as an attempt to build independent of cFE.

**Comment by BaldBeacon** [comment]
Sorry if I wasn't specific enough. This was building with the default options present in the cmake directory of the CFE. I tried my best to find the bare minimum to show the problem.

**Comment by skliper** [comment]
What's your cFE version?

**Comment by skliper** [comment]
oh.. 6.7.11?  Do a make VERBOSE=1 and see what's defined...

**Comment by jphickey** [comment]
When building CFE, did you recycle an existing `sample_defs` directory or did you copy the sample from CFE again?  We do update the example from time to time, and this would be included.

However, given that the build actually fails without this, maybe we should be forcing this definition rather than relying on a user-controlled file to provide it.  That presents another challenge, however, because its really a glibc thing and its different if you are building on BSD/Cygwin/MacOS/etc.

**Comment by BaldBeacon** [comment]
> When building CFE, did you recycle an existing sample_defs directory

I was using our previous version and it looks like _XOPEN_SOURCE=600 snuck it's way into the mission config. Adding that resolves the issue so I'll close this.
